version: "3.8"
services:
  mi:
    image: wso2/wso2mi:latest #commmunity version
    container_name: wso2mi    
    volumes:
      - ./mi-home/conf/deployment.toml:/home/wso2carbon/wso2-config-volume
    ports:
    - "8280:8280"
    - "8243:8243"
    - "9191:9191"
    - "9154:9154"